#règle utilisée pour la fusion des notices marc21 du SUDOC avec les notices de la KB
rule "Keep 035"
 when

   merge

then

   replace MARC."LDR"

   remove MARC."0"XX excluding "001,035"

   add MARC."0"XX excluding "001"

   replace MARC."1"XX

   replace MARC."2"XX

   replace MARC."3"XX

   replace MARC."4"XX

   replace MARC."5"XX

   replace MARC."6"XX

   replace MARC."7"XX

   replace MARC."8"XX

   replace MARC."9"XX

   replace MARC."035" when MARC."035"."a" contains "OCoLC" excluding MARC."035"("9","9")

end