rule "Electre"
when
 (TRUE)
then
  #Nettoyage des caractères de rejets des articles dans les titres
  replaceContents "2**.*.\u0088" with "<<"
  replaceContents "2**.*.\u0089" with ">>"
  replaceContents "2**.*.\u02C6" with "<<"
  replaceContents "2**.*.\u2030" with ">>"
  copyField "856.u" to "901.u" if (exists "856.u.*media.electre-ng.com/images/*")
  addSubField "901.a.ELECTRE" if (exists "901.u.*media.electre-ng.com/images/*")
  addSubField "901.x.Valide" if (exists "901.u.*media.electre-ng.com/images/*")
 end
