rule "ordre des champs pour les états de collections"
#############################
priority 12
when
(TRUE)
then
moveSubfieldsToEndOfField "COV" "debcanolmk" 
end
#_______________________________________

rule "Fusion des états de collection"
#############################
priority 11
when
(existsMoreThanOnce "COV")
then
addSubField "COV.0.&#32;"
combineFields "COV" excluding "8"
end
#_______________________________________

rule "Nettoyage du niveau bibliographique"
##################################
priority 10
when
 (TRUE)
then
  #Construction du champs PPN
  removeField "035" if (exists "035.9.sudoc")
  removeSubField "035.z"
  copyField  "035" to "PPN" if (exists "035.a.(PPN)*")
  replaceContents "PPN.a.(PPN)" with ""
  correctDuplicateFields "PPN"

  #Nettoyage des champs inutiles
  removeControlField "***"
  removeField "0**"
  removeField "1**"
  removeField "2**"
  removeField "3**"
  removeField "4**"
  removeField "5**"
  removeField "6**"
  removeField "7**"
  removeField "8**"
  removeField "9**"
  #Ajout du code PEB 
end
#_______________________________________

rule "Traitement des données d'inventaire institution quand le portfolio est actif"
###############################################################
priority 9
when
 (exists "PPP.{*,*}.s.Available")
then
 #Ajout code PEB
  addSubField "PPP.j.s"
  #Traitement des données d'inventaire 
  changeField "PPP" to "INV" if(exists "PPP.{*,*}.8")
  ##Création du 856
  copyField "INV" to "856" if(exists "INV.{*,*}.u")
  changeSubField "856.n" to "2"
  ##Création du 930
  copyField "INV" to "930"
  ##Création du 955
  changeField "COV" to "955" if(exists "COV.{*,*}.8")
  ###Création du 997a
  copyField "INV" to "997"
  removeField "INV"
end
#_______________________________________

rule "Traitement des données d'inventaire institution quand le portfolio est inactif"
#################################################################
priority 8
when
 (exists "PPP.{*,*}.s.Not Available")
then
  #On ajoute le code PEB
   addSubField "PPP.j.g"
  #Traitement des données d'inventaire 
  changeField "PPP" to "INV" if(exists "PPP.{*,*}.8")
  removeField "COV"
  removeField "EMB"
  ##Création de la note 319 indiquant l'indisponibilité de la collection
  copyField "INV" to "319"
  removeSubField "319.a"
  removeSubField "319.n"
   removeSubField "319.j"
  removeSubField "319.4"
  removeSubField "319.s"
  removeSubField "319.u"
  removeSubField "319.z"
  removeSubField "319.7"
  addSubField "319.a.Ressource non disponible"
  moveSubfieldsToEndOfField  "319" "8"
 ##Ajout de la note en 856 2
  copyField "INV" to "856"
  removeSubField "856.a"
  removeSubField "856.4"
  removeSubField "856.s"
  removeSubField "856.j"
  removeSubField "856.u"
  removeSubField "856.z"
  removeSubField "856.7"
  addSubField "856.2.Ressource non disponible"
  moveSubfieldsToEndOfField  "856" "8"
  ##Création du 930
  copyField "INV" to "930"
  ###Création du 997a
  copyField "INV" to "997"
  removeField "INV"
end
#_______________________________________

rule "Traitement des embargos sur les dernières annèes"
#################################################################
priority 5
when
 (exists "EMB.{*,*}.a.>")
then
  #Traitement des données d'inventaire 
  copyField "EMB.b" to "955.4"
  prefix "955.4" with "Embargo sur les "
  suffix "955.4" with " dernières années"
  combineFields "955" excluding "z"
  removeField "EMB"
 end
#_______________________________________


rule "Traitement des embargos sur les premières annèes"
#################################################################
priority 4
when
 (exists "EMB.{*,*}.a.<")
then
  #Traitement des données d'inventaire 
  copyField "EMB.b" to "955.4"
  prefix "955.4" with "Embargo sur les "
  suffix "955.4" with " premières années"
  combineFields "955" excluding "z"
  removeField "EMB"
 end
#_______________________________________



rule "Suppression du champs d'exportation  des données d'inventaires"
#########################################################
priority 3
when
 (TRUE)
then
  ### Nettoyage du 997
  removeSubField "997.n"
  removeSubField "997.s"
  removeSubField "997.4"
  removeSubField "997.u"
  removeSubField "997.j"
  removeSubField "997.z"
  removeSubField "997.a"
  changeSubField "997.7" to "a"
  moveSubfieldsToEndOfField  "997" "8"
 ### Nettoyage du 930
  removeSubField "930.n"
  removeSubField "930.s"
  removeSubField "930.a"
  removeSubField "930.b"
  removeSubField "930.4"
  removeSubField "930.u"
  removeSubField "930.z"
  removeSubField "930.7"
 #Injection du RCR
  addSubField "930.b.330009999"
 
  moveSubfieldsToEndOfField  "930" "8"
 ### Nettoyage du 955
 changeFirstIndicator "955" to "4"
 changeSecondIndicator "955" to "1"
 moveSubfieldsToEndOfField  "930" "8"
  ### Nettoyage du 856
  changeFirstIndicator "856" to "4"
  removeSubField "856.n"
  removeSubField "856.s"
  removeSubField "856.a"
  removeSubField "856.4"
   removeSubField "856.j"
  removeSubField "856.7"
  addSubField "856.z.Accès restreint aux membres de la communauté universitaire de l'établissement" if(not exists "856.{*,*}.z")
  moveSubfieldsToEndOfField  "856" "2"
  moveSubfieldsToEndOfField  "856" "8"
  removeField "PPP"
end

rule "Fusion des PPN"
#############################
priority 2
when
(existsMoreThanOnce "PPN")
then
#combineFields "PPN" excluding "8"
#changeSubFieldOnlyFirst "PPN.a" to "z"
end
#_______________________________________
