rule "Nettoyage 9##"
priority 10
when
  (TRUE)
then
  removeField "904"
  removeField "994"   
end

rule "ajoute 904.a.FRBR  sauf les notices de périodiques et les notices avec un 996a"
priority 09
when
  (not existsControl "LDR.{7,1}.s" ) AND (not exists "996.a")
then
  addField "904.a.FRBR" 
end


rule "Cree un rebond vers le SUDOC sur la base du PPN"
priority 09
when
   (exists "035.a.(PPN)*")
then
    copyField "035.a" to "SUD.u" if (exists "035.a.(PPN)*")
    replaceContents "SUD.u.(PPN)" with ""
    addSubField  "SUD.a.SUDOC"
    moveSubfieldsToEndOfField "SUD" "u" 
    changeField "SUD" to "994"
    removeField "SUD"
end


rule "Cree un rebond vers le catalogue de Bordeaux Métropole sur la base de l'ISBN"
priority  09
when
   (exists "010.a")
then
    copyField "010.a" to "CUB.u"
    combineFields "CUB" excluding "9"
    replaceContentsExceptFirst "CUB.u" with ""
    addSubField  "CUB.a.CUB"
    moveSubfieldsToEndOfField "CUB" "u"   
   changeField "CUB" to "994" if (not exists "CUB.u.TRUC")
   removeField "CUB" 
end


rule "Corrige PPN"
# Corrige les erreurs les plus fréquentes sur la saisie des PPN
priority 09
when
(true)
then
   replaceContents "035.a.p" with "P" if (exists "035.{*,*}.a")
   replaceContents "035.a.n" with "N" if (exists "035.{*,*}.a")
   replaceContents "035.a.PPP" with "PPN" if (exists "035.{*,*}.a")
   replaceContents "035.a.PNN" with "PPN" if (exists "035.{*,*}.a")
   replaceContents "035.a.NPP" with "PPN" if (exists "035.{*,*}.a")
   replaceContents "035.a.NNN" with "PPN" if (exists "035.{*,*}.a")
   replaceContents "035.a.PPN" with "(PPN)" if (exists "035.{*,*}.a")
   replaceContents "035.a.((" with "(" if (exists "035.{*,*}.a")
   replaceContents "035.a.))" with ")" if (exists "035.{*,*}.a")
   replaceContents "035.a. " with "" if (exists "035.{*,*}.a")
end




rule "On transfert les champs 200$h et $i dans un champ 902$a pour créer une clef de DEDUP"
priority 07
when
  (exists "200.h") OR (exists "200.i")
then
  removeField "902"
  addField "902.a._"
  prefixSubField "902.a" with "200.h" if (exists "902.a")
  suffixSubField "902.a" with "200.i" if (exists "902.a")
   replaceContents "902.a.^_(.*)$" with "$1"
  replaceContents "902.a.^(.*)_$" with "$1"
end

rule "Créée une clef de DEDUP avec les PPN en 035, 452, 455 et 456"
priority 07
when
  (TRUE)
then
  removeField "903"
  copyField "035.a" to "903.a" if (exists "035.a.(PPN)*")
  copyField "452.1" to "903.a" if (exists "452.1.001(PPN)*")
  copyField "455.1" to "903.a" if (exists "455.1.001(PPN)*")
//  copyField "456.1" to "903.a" if (exists "456.1.001(PPN)*")
  replaceContents "903.a.001(PPN)" with "(PPN)"
end

rule "Test ISBN 13 ISBN 10 "
priority 06
when
    not exists "073.a" AND 
    exists "010.a"
then
   //ISBN 13
    copyField "010.a" to "ISB.u"
    replaceContents "ISB.u.-" with ""
    replaceContents "ISB.u. " with ""
    suffix "ISB.u" with "__"
    replaceContents "ISB.u.^(.{13})_.*" with "!$1"
    //ISBN 10
     copyField "010.a" to "ISD.u"
    replaceContents "ISD.u.-" with ""
    replaceContents "ISD.u. " with ""
    suffix "ISD.u" with "__"
    replaceContents "ISD.u.^(.{10})_.*" with "!$1"
end

rule "Notice sans 073 Lien Amazon "
priority 05
when
    exists "010.a" AND 
    not exists "901.a.AMAZON"
then
    copyField "ISB" to "AMA" if (exists "ISB.u.!*")
    copyField "ISD" to "AMA" if (exists "ISD.u.!*")
    replaceContents "AMA.u.!" with ""
  
   // Formatage de l'URL
    addSubField "AMA.a.AMAZON"
    prefix "AMA.u" with "https://images-na.ssl-images-amazon.com/images/P/"
    suffix "AMA.u" with ".jpg"
    changeFirstIndicator "AMA" to "1"
    changeSecondIndicator "AMA" to "2"
    changeField "AMA" to "901"
end

rule "Notice a un 073 Lien AbeBooks"
priority 04
when
    exists "073.a" AND not exists "901.a.ABEBOOKS"
then
    copyField "073.a" to "ABE.u"
    addSubField "ABE.a.ABEBOOKS"
    prefix "ABE.u" with "https://pictures.abebooks.com/isbn/"
    suffix "ABE.u" with ".jpg"
    changeFirstIndicator "ABE" to "1"
    changeSecondIndicator "ABE" to "3"
    changeField "ABE" to "901"
end

rule "Notice sans 073 Lien AbeBooks"
priority 04
when
    not exists "073.a" AND 
    exists "010.a" AND 
    not exists "901.a.ABEBOOKS"
then
    copyField "ISB" to "ABE" if (exists "ISB.u.!*")
    replaceContents "ABE.u.!" with ""
    // Formatage de l'URL
    addSubField "ABE.a.ABEBOOKS"
    prefix "ABE.u" with "https://pictures.abebooks.com/isbn/"
    suffix "ABE.u" with ".jpg"
    changeFirstIndicator "ABE" to "1"
    changeSecondIndicator "ABE" to "3"
    changeField "ABE" to "901"
end

rule "Notice a un 073 Lien DECITRE"
priority 03
when
    exists "073.a" AND not exists "901.a.DECITRE"
then
    copyField "073.a" to "DEC.u"
    addSubField "DEC.a.DECITRE"
    prefix "DEC.u" with "https://products-images.di-static.com/image/jean-robert-touvron-histoire/"
    suffix "DEC.u" with "-475x500-1.webp"
    changeFirstIndicator "DEC" to "1"
    changeSecondIndicator "DEC" to "4"
    changeField "DEC" to "901"
end

rule "Notice sans 073 Lien DECITRE"
priority 03
when
    not exists "073.a" AND 
    exists "010.a" AND 
    not exists "901.a.DECITRE"
then
    copyField "ISB" to "DEC" if (exists "ISB.u.!*")
    replaceContents "DEC.u.!" with ""
    // Formatage de l'URL
    addSubField "DEC.a.DECITRE"
    prefix "DEC.u" with "https://products-images.di-static.com/image/jean-robert-touvron-histoire/"
    suffix "DEC.u" with "-475x500-1.webp"
    changeFirstIndicator "DEC" to "1"
    changeSecondIndicator "DEC" to "4"
    changeField "DEC" to "901"
end

rule "Nettoyage"
priority 02
when
    (TRUE)
then
    removeField "ISB"
    removeField "ISD"
end
